### ISSUE TITLE
Sometimes data downloader crashes and causes disruptions with data ingestion.

### ISSUE THREAD

**Issue by dgarciabriseno** [Helioviewer-Project/api#99]
Traceback (most recent call last):
  File "/var/www/api.helioviewer.org/install/downloader.py", line 189, in <module>
    sys.exit(main())
  File "/var/www/api.helioviewer.org/install/downloader.py", line 68, in main
    daemon.start(args.start, args.end, args.backfill)
  File "/var/www/api.helioviewer.org/install/helioviewer/hvpull/net/daemon.py", line 152, in start
    self.query(starttime, now)
  File "/var/www/api.helioviewer.org/install/helioviewer/hvpull/net/daemon.py", line 326, in query
    self.acquire(new_urls)
  File "/var/www/api.helioviewer.org/install/helioviewer/hvpull/net/daemon.py", line 449, in acquire
    self.ingest(finished)
  File "/var/www/api.helioviewer.org/install/helioviewer/hvpull/net/daemon.py", line 490, in ingest
    mark_as_corrupt(self._cursor, filename, e.get_message())
  File "/var/www/api.helioviewer.org/install/helioviewer/db.py", line 990, in mark_as_corrupt
    cursor.execute(sql)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 226, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1048, "Column 'timestamp' cannot be null")

**Comment by dgarciabriseno** [comment]
This commit fixed the above error ed1a4c1faa9d4edce1762dc079d5b7b9cbbaa494
And this commit fixes other errors I've seen 967cfba939c440633406fcd424ce5d5cda698c11
Downloaders are far more stable now.
